?? HOW TO IDENTIFY DP PROBLEMS 
1. Choice
2. Optimal ans 

?? RECURSIVE FUNCTION CAN BE OPTIMIZED IN 
1. Memoization 
2. Top - Down 

>>>>>>> DP PARENT QUESTIONS 
1. O/1 KNAPSACK (6) 
2. UNBOUNDED KNAPSACK  (5) 
3. FIBONACCI  (7) 
4. LCS  (15) 
5. LIS   (10) 
6. KADANE'S ALGORITHM  (6) 
7. MATRIX CHAIN MULTIPLICATION   (7) 
8. DP ON  TREES (4) 
9. DP ON GRID (14) 
10. OTHERS (5) 

KNAPSACK PROBLEMS TYPES 
1. FRACTIONAL KNAPSACK (GREEDY) 
2. O/1 KNAPSACK 
3. UNBOUNDED KNAPSACK (UNLIMITED SUPPLY OR MULTIPLE OCCURENCES OF ITEMS ARE ALLOWED)

  
>>>>>>>>>>>> 0/1 KNAPSACK PROBLEMS 
1. SUBSET SUM 
2. EQUAL SUM PARTITION 
3. COUNT OF SUBSET SUM 
4. MINIMUM SUBSET SUM DIFF 
5. TARGET SUM 
6. NO. OF SUBSET WITH DIFFERENCE
